name: Heroku Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  heroku_deploy:
    # https://github.com/marketplace/actions/deploy-to-heroku
    name: ⚛️ Heroku Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action

        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name:  ${{ secrets.HEROKU_AUTH_API_ID }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          NODE_ENV: production
          JWT_JWT_TOKEN_KEY: ${{ secrets.JWT_JWT_TOKEN_KEY }}
          API_IMAGES_URL: ${{ secrets.MONGO_URI_IMAGES }}